name: Build Word files

on: [push, pull_request]

env:
  PDC_VER: "2.17.1.1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup pandoc
        run: |
          echo "Installing pandoc version ${PDC_VER}"
          wget -qO- https://github.com/jgm/pandoc/releases/download/${PDC_VER}/pandoc-${PDC_VER}-linux-amd64.tar.gz | sudo tar xvzf - --strip-components 1 -C /usr/local/
      - name: Build docx files
        run: |
          find ./docs -type f -name "*.md" -print0 | parallel -0 -j2 pandoc -s {} -o {}.docx
      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.9.1
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./docs
          publish_branch: docx
